from django.utils.translation import gettext_lazy as _

EXAMPLE_CHOICE_NOT_DEFINED = -1
EXAMPLE_CHOICE_ZERO = 0
EXAMPLE_CHOICE_ONE = 1
EXAMPLE_CHOICE = (
    (EXAMPLE_CHOICE_NOT_DEFINED, _("EXAMPLE CHOICE NOT DEFINED")),
    (EXAMPLE_CHOICE_ZERO, _("EXAMPLE CHOICE ZERO")),
    (EXAMPLE_CHOICE_ONE, _("EXAMPLE CHOICE ONE")),
)


MESSAGE_EVENT_NOT_DEFINED = 1
MESSAGE_EVENT_NEW_ANSWER = 2


MESSAGE_EVENTS = (
    (MESSAGE_EVENT_NOT_DEFINED, _("Not Defined")),
    (MESSAGE_EVENT_NEW_ANSWER, _("New Answer")),
)
